- hosts: master
  become: yes
  tasks:
    - name: Create tmp folder
      shell: mkdir tmp && cd tmp

    - name: Pull helm installation script
      shell:  curl {{ helm_setup_script }} > install-helm.sh

    - name: Changing permission of "install-helm.sh", adding "+x"
      file: dest=install-helm.sh mode=a+x

    - name: Start helm installation
      shell: ./install-helm.sh

    - name:  Add stable helm chart repo
      shell: helm repo add stable {{ helm_default_repository }}
      