- hosts: all
  become: yes
  gather_facts: false
  tasks:
    - name: Disable Swap
      shell: swapoff -a

    - name: Install Docker dependencies
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present
        update_cache: true

    - name: Add Docker registry
      shell: "yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"

    - name: Install Docker container runtime
      yum:
        name:
          - docker-ce-19.03.4
          - docker-ce-cli-19.03.4
          - containerd.io-1.2.10
        state: present
        update_cache: true

    - name: Install other required packages
      yum:
        name:
          - epel-release
          - python3
          - curl
          - telnet
        state: present

    - name: Create /etc/docker directory
      shell: mkdir /etc/docker

    - name: Setup Docker Daemon
      shell: |
        cat > /etc/docker/daemon.json <<EOF
        {
          "exec-opts": ["native.cgroupdriver=systemd"],
          "log-driver": "json-file",
          "log-opts": {
            "max-size": "100m"
          },
          "storage-driver": "overlay2",
          "storage-opts": [
            "overlay2.override_kernel_check=true"
          ]
        }
        EOF

    - name: Make directroy for docker systemd
      shell: mkdir -p /etc/systemd/system/docker.service.d

    - name: Enabled docker
      systemd:
        name: docker
        enabled: yes

    - name: Enable br_netfitter module
      shell: modprobe br_netfilter

    - name: Letting iptables see bridged traffic
      shell: |
        cat > /etc/sysctl.d/99-kubernetes-cri.conf <<EOF
        net.bridge.bridge-nf-call-iptables  = 1
        net.ipv4.ip_forward                 = 1
        net.bridge.bridge-nf-call-ip6tables = 1
        EOF

    - name: Refresh sysctl config variables
      shell: sysctl --system

    - name: Restart docker
      systemd:
        state: restarted
        daemon_reload: yes
        name: docker
