- hosts: master
  become: yes
  tasks:
    - name: Install kubectl for Master node
      yum:
        name:
          - kubectl
        disable_excludes: kubernetes
        state: present

    - name: Initialize the cluster
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: Create .kube directory
      become: yes
      become_user: centos
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: Copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/centos/.kube/config
        remote_src: yes
        owner: centos

    - name: Install Pod network
      become: yes
      become_user: centos
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/2140ac876ef134e0ed5af15c65e414cf26827915/Documentation/kube-flannel.yml
      args:
        chdir: $HOME
        creates: pod_network_setup.txt

    - name: Restart kubelet
      systemd:
        name: kubelet
        state: restarted
        enabled: yes